apiVersion: apps/v1
kind: Deployment

metadata:
  name: college-notice-board

spec:
  replicas: 2

  selector:
    matchLabels:
      app: college-notice-board

  template:
    metadata:
      labels:
        app: college-notice-board

    spec:
      containers:
        - name: college-notice-board
          image: YOUR_DOCKERHUB_USERNAME/college-notice-board:1.0
          ports:
            - containerPort: 80
